name: Build
on:
  workflow_call:
    inputs:
      v8_version:
        type: string
        required: true
      
      edt_version:
        type: string
        required: true
      
      artifact_name:
        type: string
        required: true
jobs:
  build-dev:
  
    runs-on: ubuntu-20.04

    steps:

    - uses: actions/checkout@v3
    
    - name: prepare
      run: |
        mkdir export
        mkdir binary
        mkdir file-db
        mkdir reports
    
    - name: install EDT
      uses: IT-Medved/onec-setup-build-env-action@develop
      with:
        type: edt
        edt_version: ${{ inputs.edt_version }}
        cache: true
      env: 
        ONEC_USERNAME: ${{ secrets.ONEC_USERNAME }}
        ONEC_PASSWORD: ${{ secrets.ONEC_PASSWORD }}
      timeout-minutes: 10
    
    - name: install Onec Platform
      uses: IT-Medved/onec-setup-build-env-action@develop
      with:
        type: onec
        onec_version: ${{ inputs.v8_version }}
        cache: false
      env: 
        ONEC_USERNAME: ${{ secrets.ONEC_USERNAME }}
        ONEC_PASSWORD: ${{ secrets.ONEC_PASSWORD }}
      timeout-minutes: 10
        
    - name: export configuration
      uses: IT-Medved/onec-edtcli-command-action@feature/init
      with:
        export: true
        from: fixtures/demo-configuration
        to: export/configuration
      timeout-minutes: 5
      
    - name: export yaxunit extension
      uses: IT-Medved/onec-edtcli-command-action@feature/init
      with:
        export: true
        from: exts/yaxunit
        to: export/yaxunit
      timeout-minutes: 5
      
    - name: export tests extension
      uses: IT-Medved/onec-edtcli-command-action@feature/init
      with:
        export: true
        from: tests
        to: export/tests
      timeout-minutes: 5
      
    - name: create IB
      run: ibcmd infobase create --db-path=file-db --import=export/configuration --apply --force
      timeout-minutes: 5

    - name: import yaxunit
      run: |
        ibcmd infobase config import --db-path=file-db --extension=YAXUNIT export/yaxunit
        ibcmd infobase config apply --db-path=file-db --extension=YAXUNIT --force
        ibcmd infobase config extension update --db-path=file-db --name=YAXUNIT --safe-mode=no --unsafe-action-protection=no
      timeout-minutes: 5

    - name: import tests
      run: |
        ibcmd infobase config import --db-path=file-db --extension=tests export/tests
        ibcmd infobase config apply --db-path=file-db --extension=tests --force
        ibcmd infobase config extension update --db-path=file-db --name=tests --safe-mode=no --unsafe-action-protection=no
      timeout-minutes: 5

    - name: save yaxunit
      run: ibcmd infobase config save --db-path=file-db --extension=YAXUNIT binary/yaxunit.cfe
      timeout-minutes: 5
      
    - name: save yaxunit
      run: ibcmd infobase config save --db-path=file-db --extension=tests binary/tests.cfe
      timeout-minutes: 5
      
    - name: save yaxunit
      run: ibcmd infobase config save --db-path=file-db binary/configuration.cf
      timeout-minutes: 5
      
    - name: upload-artifact
      uses: actions/upload-artifact@v3
      with:
        name: ${{ inputs.artifact_name }}
        path: binary/*.*
