name: Build and test
on:
  push:
    branches: [ feature/**, develop ]
concurrency:
  group: ${{ github.workflow }}-${{ github.ref }}
  cancel-in-progress: true

env:
  v8_version: 8.3.21.1895

jobs:
  build_artifacts:
    name: Build artifacts
    uses: ./.github/workflows/build.yml
    with:
      v8_version: ${{ env.v8_version }}
      edt_version: 2023.1.2
      artifact_name: build-artifacts
    secrets: inherit
  
  tests_linux_ru:
    name: Test on Linux ${{ env.v8_version }} ru_RU
    uses: ./.github/workflows/run-tests-linux.yml
    need: build-artifacts
    with:
      v8_version: ${{ env.v8_version }}
      artifact_name: build-artifacts
    secrets: inherit
  
  tests_linux_en:
    name: Test on Linux ${{ env.v8_version }} en_US
    uses: ./.github/workflows/run-tests-linux.yml
    need: build-artifacts
    with:
      v8_version: ${{ env.v8_version }}
      artifact_name: build-artifacts
      locale: en_US
    secrets: inherit
  
  tests_windows_ru:
    name: Test on Windows ${{ env.v8_version }} ru_RU
     uses: ./.github/workflows/run-tests-windows.yml
    need: build-artifacts
    with:
      v8_version: ${{ env.v8_version }}
      artifact_name: build-artifacts
    secrets: inherit
  
  tests_macos_ru:
    name: Test on MacOS ${{ env.v8_version }} ru_RU
    uses: ./.github/workflows/run-tests-macos.yml
    need: build-artifacts
    with:
      v8_version: ${{ env.v8_version }}
      artifact_name: build-artifacts
    secrets: inherit
