name: Run tests on Linux

on:
  workflow_call:
    inputs:
      
      matrix:
        description: 'Matrix parameters'
        type: string
        required: true
      
      artifact_name:
        type: string
        required: false
        default: build-artifacts
        
      fail_on_failure:
        type: boolean
        required: false
        default: true

permissions:
    contents: read
    checks: write
    id-token: write

concurrency:
  group: ${{ github.workflow }}-${{ github.ref }}-${{ github.event.number }}
  cancel-in-progress: true

jobs:
  tests_windows:
    uses: ./.github/workflows/step-run-tests-windows.yml
    with:
      matrix: ${{ inputs.matrix }}
    secrets: inherit
  
  tests_ubuntu:
    uses: ./.github/workflows/step-run-tests-linux.yml
    with:
      matrix: ${{ inputs.matrix }}
    secrets: inherit